package alex;

public enum ClaseLexica {
 INT, BOOL, CHAR, TRUE, FALSE, FLOAT, VECTOR, CREAVECTOR, 
 SIZE, WHILE, DO, THEN, IF, ELSE, PROC, FUN, RETURN, 
 STRUCT, TYPEDEF, ENUM, IDEN, ENT, REAL, CARACTER, SUMA, RESTA,
 MUL, DIVREAL, DIVENT, MODULO, AND, OR, NOT, MENOR, 
 MAYOR, MENORIGUAL, MAYORIGUAL, IGUALIGUAL, DISTINTO, PUNTO, 
 LLAVESAP, LLAVESCIERRE, BARRA, PAP, PCIERRE, IGUAL, COMA, 
 EOF, PUNTOYCOMA, CORCHETEAP, CORCHETECIERRE
}
