
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Feb 26 18:24:41 CET 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 11;
  public static final int MENOS = 5;
  public static final int IGUALIGUAL = 19;
  public static final int MENOR = 18;
  public static final int IGUAL = 8;
  public static final int CONCAT = 20;
  public static final int IDEN = 2;
  public static final int LMAP = 14;
  public static final int POR = 6;
  public static final int COMA = 9;
  public static final int MAYOR = 17;
  public static final int DISTINTO = 16;
  public static final int EOF = 0;
  public static final int LFILTER = 13;
  public static final int LREDUCE = 15;
  public static final int DIV = 7;
  public static final int PAP = 10;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int CORCHETEABRE = 21;
  public static final int ENT = 3;
  public static final int CORCHETECIERRA = 22;
  public static final int MAS = 4;
}

