
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Apr 29 00:36:53 CEST 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 46;
  public static final int CREAVECTOR = 4;
  public static final int DISTINTO = 34;
  public static final int DIVENT = 24;
  public static final int CHAR = 55;
  public static final int PUNTOYCOMA = 43;
  public static final int PCIERRE = 40;
  public static final int CASE = 9;
  public static final int RESTA = 21;
  public static final int INT = 53;
  public static final int FOR = 7;
  public static final int NOT = 28;
  public static final int MENORIGUAL = 31;
  public static final int AND = 26;
  public static final int IGUAL = 41;
  public static final int CARACTER = 52;
  public static final int FUN = 15;
  public static final int OR = 27;
  public static final int BOOL = 54;
  public static final int CALL = 12;
  public static final int SUMA = 20;
  public static final int TYPEDEF = 18;
  public static final int IF = 11;
  public static final int AMPERSAND = 48;
  public static final int MAYORIGUAL = 32;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int SIZE = 5;
  public static final int TRUE = 2;
  public static final int error = 1;
  public static final int COMA = 42;
  public static final int MUL = 22;
  public static final int MODULO = 25;
  public static final int MENOR = 29;
  public static final int BREAK = 10;
  public static final int VECTOR = 57;
  public static final int SWITCH = 8;
  public static final int REAL = 51;
  public static final int MAYOR = 30;
  public static final int ENT = 50;
  public static final int PAP = 39;
  public static final int BARRA = 38;
  public static final int ELSE = 13;
  public static final int CORCHETECIERRE = 45;
  public static final int PUNTO = 35;
  public static final int ENUM = 19;
  public static final int IDEN = 49;
  public static final int IGUALIGUAL = 33;
  public static final int WHILE = 6;
  public static final int DEFAULT = 47;
  public static final int LLAVESAP = 36;
  public static final int FLOAT = 56;
  public static final int LLAVESCIERRE = 37;
  public static final int CORCHETEAP = 44;
  public static final int PROC = 14;
  public static final int FALSE = 3;
  public static final int STRUCT = 17;
  public static final int DIVREAL = 23;
}

