
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Apr 08 19:46:18 CEST 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 51;
  public static final int CREAVECTOR = 9;
  public static final int DISTINTO = 39;
  public static final int DIVENT = 29;
  public static final int CHAR = 4;
  public static final int PUNTOYCOMA = 48;
  public static final int PCIERRE = 45;
  public static final int CASE = 14;
  public static final int RESTA = 26;
  public static final int INT = 2;
  public static final int FOR = 12;
  public static final int MENORIGUAL = 36;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int IGUAL = 46;
  public static final int CARACTER = 56;
  public static final int FUN = 20;
  public static final int OR = 32;
  public static final int BOOL = 3;
  public static final int CALL = 17;
  public static final int SUMA = 25;
  public static final int TYPEDEF = 23;
  public static final int IF = 16;
  public static final int MAYORIGUAL = 37;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int SIZE = 10;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int COMA = 47;
  public static final int MUL = 27;
  public static final int MODULO = 30;
  public static final int MENOR = 34;
  public static final int BREAK = 15;
  public static final int VECTOR = 8;
  public static final int SWITCH = 13;
  public static final int REAL = 55;
  public static final int MAYOR = 35;
  public static final int ENT = 54;
  public static final int PAP = 44;
  public static final int BARRA = 43;
  public static final int ELSE = 18;
  public static final int CORCHETECIERRE = 50;
  public static final int PUNTO = 40;
  public static final int ENUM = 24;
  public static final int IDEN = 53;
  public static final int IGUALIGUAL = 38;
  public static final int WHILE = 11;
  public static final int DEFAULT = 52;
  public static final int LLAVESAP = 41;
  public static final int FLOAT = 7;
  public static final int LLAVESCIERRE = 42;
  public static final int CORCHETEAP = 49;
  public static final int PROC = 19;
  public static final int FALSE = 6;
  public static final int STRUCT = 22;
  public static final int DIVREAL = 28;
}

