
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Apr 04 23:34:21 CEST 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int CREAVECTOR = 9;
  public static final int DISTINTO = 41;
  public static final int DIVENT = 31;
  public static final int CHAR = 4;
  public static final int PUNTOYCOMA = 50;
  public static final int PCIERRE = 47;
  public static final int RESTA = 28;
  public static final int INT = 2;
  public static final int MENORIGUAL = 38;
  public static final int NOT = 35;
  public static final int AND = 33;
  public static final int IGUAL = 48;
  public static final int FUN = 18;
  public static final int CARACTER = 26;
  public static final int OR = 34;
  public static final int BOOL = 3;
  public static final int CALL = 15;
  public static final int SUMA = 27;
  public static final int TYPEDEF = 21;
  public static final int IF = 14;
  public static final int MAYORIGUAL = 39;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int SIZE = 10;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int MUL = 29;
  public static final int MODULO = 32;
  public static final int MENOR = 36;
  public static final int VECTOR = 8;
  public static final int MAYOR = 37;
  public static final int REAL = 25;
  public static final int ENT = 24;
  public static final int PAP = 46;
  public static final int BARRA = 45;
  public static final int ELSE = 16;
  public static final int CORCHETECIERRE = 52;
  public static final int PUNTO = 42;
  public static final int ENUM = 22;
  public static final int IGUALIGUAL = 40;
  public static final int IDEN = 23;
  public static final int WHILE = 11;
  public static final int LLAVESAP = 43;
  public static final int FLOAT = 7;
  public static final int LLAVESCIERRE = 44;
  public static final int THEN = 13;
  public static final int CORCHETEAP = 51;
  public static final int PROC = 17;
  public static final int FALSE = 6;
  public static final int STRUCT = 20;
  public static final int DO = 12;
  public static final int DIVREAL = 30;
}

